<a href="https://colab.research.google.com/github/nikhilRajput-prog/PyTorch/blob/main/3Practical_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [180]:
#we will build a simple nn
#train it on a world dataset
#will mimic the pytorch workflow
#will have a lot of manual elements
#end result is not important
#pytorch training pipeline

In [181]:
''' load the dataset
basic processing
training process
    create the model
    forward pass
    loss calculation
    backprop
    parameters update
model evaluation'''

' load the dataset\nbasic processing\ntraining process\n    create the model\n    forward pass\n    loss calculation\n    backprop\n    parameters update\nmodel evaluation'

In [182]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [183]:
df=pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [184]:
df.shape

(569, 33)

In [185]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [186]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [187]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [188]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [189]:
X_train

array([[ 0.58565351, -0.12675316,  0.67752313, ...,  0.92401626,
        -0.21333543,  1.33092195],
       [-0.30441894, -0.00425286, -0.38209711, ..., -1.59569796,
        -0.73036711, -1.19892307],
       [ 0.26757119, -0.66666189,  0.30449149, ...,  0.44367096,
        -0.49450069, -0.33058189],
       ...,
       [-0.70620714, -0.75059728, -0.6713787 , ..., -0.05066498,
        -0.18678093, -0.53572021],
       [-0.78991301, -0.06550301, -0.8194585 , ..., -0.68630638,
        -0.79128625, -0.99378475],
       [ 0.32337511,  1.34778748,  0.41858576, ...,  1.3779348 ,
         1.75013531,  0.89150634]])

In [190]:
y_train

283    M
58     B
128    B
133    B
323    M
      ..
91     M
557    B
422    B
67     B
28     M
Name: diagnosis, Length: 455, dtype: object

In [191]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [192]:
y_train

array([1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1])

In [193]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [194]:
x_train_tensor.shape

torch.Size([455, 30])

In [195]:
y_train_tensor.shape

torch.Size([455])

#MODEL

In [196]:
class SimpleNeuralNetwork():

  def __init__(self, X):

    self.layer_weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.layer_bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def predict(self, X):
    z = torch.matmul(X, self.layer_weights) + self.layer_bias
    predictions = torch.sigmoid(z)
    return predictions

  def calculate_loss(self, predictions, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    predictions = torch.clamp(predictions, epsilon, 1 - epsilon)

    # Calculate loss
    current_loss = -(y_train_tensor * torch.log(predictions) + (1 - y_train_tensor) * torch.log(1 - predictions)).mean()
    return current_loss

In [197]:
optimizer_lr=0.1
num_epochs=25

In [198]:
# create model
neural_network_model = SimpleNeuralNetwork(X_train_tensor)

# define loop
for current_epoch in range(num_epochs):

  # forward pass
  predictions = neural_network_model.predict(X_train_tensor)

  # loss calculate
  current_loss = neural_network_model.calculate_loss(predictions, y_train_tensor)

  # backward pass
  current_loss.backward()

  # parameters update
  with torch.no_grad():
    neural_network_model.layer_weights -= optimizer_lr * neural_network_model.layer_weights.grad
    neural_network_model.layer_bias -= optimizer_lr * neural_network_model.layer_bias.grad

  # zero gradients
  neural_network_model.layer_weights.grad.zero_()
  neural_network_model.layer_bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {current_epoch + 1}, Loss: {current_loss.item()}')

Epoch: 1, Loss: 3.992468583900515
Epoch: 2, Loss: 3.884516784821759
Epoch: 3, Loss: 3.769653422920647
Epoch: 4, Loss: 3.6500048713820155
Epoch: 5, Loss: 3.5239295046374144
Epoch: 6, Loss: 3.388445536601461
Epoch: 7, Loss: 3.244143768076793
Epoch: 8, Loss: 3.0934243986728673
Epoch: 9, Loss: 2.943293491296446
Epoch: 10, Loss: 2.7866565871424926
Epoch: 11, Loss: 2.6229875621953505
Epoch: 12, Loss: 2.4552584063707394
Epoch: 13, Loss: 2.287465021261902
Epoch: 14, Loss: 2.121064313862037
Epoch: 15, Loss: 1.9540212015185938
Epoch: 16, Loss: 1.7844027476802065
Epoch: 17, Loss: 1.6236549035905854
Epoch: 18, Loss: 1.469684550215105
Epoch: 19, Loss: 1.3236236790712113
Epoch: 20, Loss: 1.1937283960618135
Epoch: 21, Loss: 1.0820032925777756
Epoch: 22, Loss: 0.9897245430072658
Epoch: 23, Loss: 0.9170242985653351
Epoch: 24, Loss: 0.8625626345220611
Epoch: 25, Loss: 0.8235971575775627

In [199]:
# model evaluation
with torch.no_grad():
  predictions = neural_network_model.predict(X_test_tensor)
  predictions = (predictions > 0.9).float()
  accuracy = (predictions == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6100338697433472